language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install tox
  - pip install tox-travis
  - pip install detox
  - pip install pytest-datafiles
# command to run tests
script:
  - detox # or py.test for Python versions 3.5 and below